export const defaultCompanyItem = {
  id: '',
  state_name: '',
  name: '',
  type_name: '',
  registration_date: '',
  registration_number: '',
  status: { id: 0, name: '' },
  taxId: '',
  line1: '',
  line2: '',
  line3: '',
  line4: '',
  city: '',
  country: { id: 0, short_name: '', full_name: '' },
  state: { id: 0, abbreviation: '', name: '' },
  type: { id: 0, name: '', full_name: null },
  zip: '',
  logo: '',
  ein: null,
};
