export const ROUTES = {
  REDIRECT: '*',
  DEFAULT: '/',
  LOGIN: '/login',
  HOME: '/home',
  RECOVERY_PASS: '/recovery_password',
  RECOVERY_PASS_CONFIRM: '/recovery_password_confirmation',
  CREATE_COMPANY: '/create_company',
  ACCOUNT: '/account',
  COMPANY: '/company',
  MAIL: '/mail',
  DOCUMENTS: '/documents',
  SERVICES: '/services',
  ORDERS: '/orders',
  INVOICES: '/invoices',
  EIN: '/ein',
};
